import imgGetProfit from '../../assets/Image-1.png';
import imgConnectGain from '../../assets/image 291.png';
import imgConnectGainDiscount from '../../assets/image 291-1.png';
import imgMalka from '../../assets/Image-2.png';
import imgBitRobos from '../../assets/Image-3.png';
import type { StrategyCardProps } from './StrategyCard';

export const STRATEGIES: StrategyCardProps[] = [
  {
    thumbnail: imgBitRobos,
    name: 'BIT - Robôs Investidores',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.5,
    ratingCount: 186,
    assets: ['WINFUT'],
    operations: { total: 974, wins: 823, losses: 151 },
    strategiesCount: 2,
    operatingSince: 'mar/2025',
    resultValue: '172.40 pts',
    price: 'R$ 272,99',
  },
  {
    thumbnail: imgConnectGain,
    name: 'ConnectGain Master Pass',
    planName: 'Copy Invest | ConnectGain Pass',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    assets: ['WDOFUT', 'WINFUT'],
    operations: { total: 475, wins: 323, losses: 152 },
    strategiesCount: 2,
    operatingSince: 'mar/2025',
    resultValue: '+172.40 pts',
    price: 'R$ 2.150,00',
    featured: true,
  },
  {
    thumbnail: imgBitRobos,
    name: 'BIT - Robôs Investidores',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.5,
    ratingCount: 186,
    assets: ['WINFUT'],
    operations: { total: 974, wins: 823, losses: 151 },
    resultValue: '172.40 pts',
    price: 'R$ 272,99',
  },
  {
    thumbnail: imgGetProfit,
    name: 'Get Profit One',
    planName: 'Copy Invest | Get Profit One',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.5,
    ratingCount: 186,
    assets: ['WINFUT'],
    operations: { total: 974, wins: 823, losses: 151 },
    resultValue: '-25.61 pts',
    price: 'R$ 272,99',
  },
  {
    thumbnail: imgConnectGainDiscount,
    name: 'ConnectGain Master Pass',
    planName: 'Copy Invest | ConnectGain Pass',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    assets: ['WDOFUT', 'WINFUT'],
    operations: { total: 475, wins: 323, losses: 152 },
    strategiesCount: 2,
    operatingSince: 'mar/2025',
    resultValue: '+172.40 pts',
    price: 'R$ 2.150,00',
    discountLabel: '-50%',
  },
  {
    thumbnail: imgMalka,
    name: 'MK Moderada',
    planName: 'Copy Invest | Malka Investimentos Principal',
    description: 'Foco em tendências com gestão ativa de risco.',
    rating: 4.9,
    ratingCount: 43,
    assets: ['WINQ25', 'WINFUT'],
    operations: { total: 355, wins: 210, losses: 145 },
    strategiesCount: 3,
    operatingSince: 'abr/2023',
    resultValue: '51.24 pts',
    price: 'R$ 155,10',
  },
  {
    thumbnail: imgBitRobos,
    name: 'BIGBIT',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Participe do pré-lançamento e receba benefícios exclusivos!',
    assets: [],
    waitingList: true,
  },
  {
    thumbnail: imgGetProfit,
    name: 'Get Profit One',
    planName: 'Copy Invest | Get Profit One',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.2,
    ratingCount: 98,
    assets: ['WINFUT'],
    operations: { total: 612, wins: 401, losses: 211 },
    strategiesCount: 1,
    operatingSince: 'jun/2024',
    resultValue: '87.15 pts',
    price: 'R$ 189,90',
  },
  {
    thumbnail: imgMalka,
    name: 'MK Moderada',
    planName: 'Copy Invest | Malka Investimentos Principal',
    description: 'Foco em tendências com gestão ativa de risco.',
    rating: 4.9,
    ratingCount: 43,
    assets: ['WINQ25', 'WINFUT'],
    operations: { total: 355, wins: 210, losses: 145 },
    strategiesCount: 3,
    operatingSince: 'abr/2023',
    resultValue: '-12.34 pts',
    price: 'R$ 155,10',
  },
  {
    thumbnail: imgConnectGain,
    name: 'ConnectGain Master Pass',
    planName: 'Copy Invest | ConnectGain Pass',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.3,
    ratingCount: 67,
    assets: ['WDOFUT', 'WINFUT'],
    operations: { total: 288, wins: 190, losses: 98 },
    strategiesCount: 2,
    operatingSince: 'jan/2025',
    resultValue: '204.10 pts',
    price: 'R$ 2.150,00',
  },
  {
    thumbnail: imgBitRobos,
    name: 'BIT - Robôs Investidores',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.5,
    ratingCount: 186,
    assets: ['WINFUT'],
    operations: { total: 974, wins: 823, losses: 151 },
    resultValue: '32.60 pts',
    price: 'R$ 272,99',
  },
  {
    thumbnail: imgGetProfit,
    name: 'Get Profit One',
    planName: 'Copy Invest | Get Profit One',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.0,
    ratingCount: 54,
    assets: ['WINFUT'],
    operations: { total: 421, wins: 260, losses: 161 },
    strategiesCount: 1,
    operatingSince: 'set/2024',
    resultValue: '-45.90 pts',
    price: 'R$ 189,90',
  },
  {
    thumbnail: imgConnectGainDiscount,
    name: 'ConnectGain Master Pass',
    planName: 'Copy Invest | ConnectGain Pass',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    assets: ['WDOFUT', 'WINFUT'],
    operations: { total: 475, wins: 323, losses: 152 },
    strategiesCount: 2,
    operatingSince: 'mar/2025',
    resultValue: '+99.20 pts',
    price: 'R$ 2.150,00',
    discountLabel: '-30%',
  },
  {
    thumbnail: imgMalka,
    name: 'MK Moderada',
    planName: 'Copy Invest | Malka Investimentos Principal',
    description: 'Foco em tendências com gestão ativa de risco.',
    rating: 4.7,
    ratingCount: 121,
    assets: ['WINQ25', 'WINFUT'],
    operations: { total: 502, wins: 340, losses: 162 },
    strategiesCount: 3,
    operatingSince: 'abr/2023',
    resultValue: '61.05 pts',
    price: 'R$ 155,10',
  },
  {
    thumbnail: imgBitRobos,
    name: 'BIT - Robôs Investidores',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.6,
    ratingCount: 210,
    assets: ['WINFUT'],
    operations: { total: 830, wins: 640, losses: 190 },
    strategiesCount: 2,
    operatingSince: 'fev/2024',
    resultValue: '145.75 pts',
    price: 'R$ 272,99',
  },
];
