import imgGetProfit from '../../assets/Image-1.png';
import imgConnectGain from '../../assets/image 291.png';
import imgConnectGainDiscount from '../../assets/image 291-1.png';
import imgMalka from '../../assets/Image-2.png';
import imgBitRobos from '../../assets/Image-3.png';
import type { StrategyCardProps } from './StrategyCard';

export const STRATEGIES: StrategyCardProps[] = [
  {
    thumbnail: imgBitRobos,
    name: 'BIT - Robôs Investidores',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.5,
    ratingCount: 186,
    assets: ['WINFUT'],
    operations: { total: 974, wins: 823, losses: 151 },
    strategiesCount: 2,
    operatingSince: 'mar/2025',
    resultPoints: 172.40,
    price: 'R$ 272,99',
  },
  {
    thumbnail: imgConnectGain,
    name: 'ConnectGain Master Pass',
    planName: 'Copy Invest | ConnectGain Pass',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    assets: ['WDOFUT', 'WINFUT'],
    operations: { total: 475, wins: 323, losses: 152 },
    strategiesCount: 2,
    operatingSince: 'mar/2025',
    resultPoints: 172.40,
    price: 'R$ 2.150,00',
    featured: true,
  },
  {
    thumbnail: imgBitRobos,
    name: 'BIT - Robôs Investidores',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.5,
    ratingCount: 186,
    assets: ['WINFUT'],
    operations: { total: 974, wins: 823, losses: 151 },
    resultPoints: 172.40,
    price: 'R$ 272,99',
  },
  {
    thumbnail: imgGetProfit,
    name: 'Get Profit One',
    planName: 'Copy Invest | Get Profit One',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.5,
    ratingCount: 186,
    assets: ['WINFUT'],
    operations: { total: 974, wins: 823, losses: 151 },
    resultPoints: -25.61,
    price: 'R$ 272,99',
  },
  {
    thumbnail: imgConnectGainDiscount,
    name: 'ConnectGain Master Pass',
    planName: 'Copy Invest | ConnectGain Pass',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    assets: ['WDOFUT', 'WINFUT'],
    operations: { total: 475, wins: 323, losses: 152 },
    strategiesCount: 2,
    operatingSince: 'mar/2025',
    resultPoints: 172.40,
    price: 'R$ 2.150,00',
    discountLabel: '-50%',
  },
  {
    thumbnail: imgMalka,
    name: 'MK Moderada',
    planName: 'Copy Invest | Malka Investimentos Principal',
    description: 'Foco em tendências com gestão ativa de risco.',
    rating: 4.9,
    ratingCount: 43,
    assets: ['WINQ25', 'WINFUT'],
    operations: { total: 355, wins: 210, losses: 145 },
    strategiesCount: 3,
    operatingSince: 'abr/2023',
    resultPoints: 51.24,
    price: 'R$ 155,10',
  },
  {
    thumbnail: imgBitRobos,
    name: 'BIGBIT',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Participe do pré-lançamento e receba benefícios exclusivos!',
    assets: [],
    waitingList: true,
  },
  {
    thumbnail: imgGetProfit,
    name: 'Get Profit One',
    planName: 'Copy Invest | Get Profit One',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.2,
    ratingCount: 98,
    assets: ['WINFUT'],
    operations: { total: 612, wins: 401, losses: 211 },
    strategiesCount: 1,
    operatingSince: 'jun/2024',
    resultPoints: 87.15,
    price: 'R$ 189,90',
  },
  {
    thumbnail: imgMalka,
    name: 'MK Moderada',
    planName: 'Copy Invest | Malka Investimentos Principal',
    description: 'Foco em tendências com gestão ativa de risco.',
    rating: 4.9,
    ratingCount: 43,
    assets: ['WINQ25', 'WINFUT'],
    operations: { total: 355, wins: 210, losses: 145 },
    strategiesCount: 3,
    operatingSince: 'abr/2023',
    resultPoints: -12.34,
    price: 'R$ 155,10',
  },
  {
    thumbnail: imgConnectGain,
    name: 'ConnectGain Master Pass',
    planName: 'Copy Invest | ConnectGain Pass',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.3,
    ratingCount: 67,
    assets: ['WDOFUT', 'WINFUT'],
    operations: { total: 288, wins: 190, losses: 98 },
    strategiesCount: 2,
    operatingSince: 'jan/2025',
    resultPoints: 204.10,
    price: 'R$ 2.150,00',
  },
  {
    thumbnail: imgBitRobos,
    name: 'BIT - Robôs Investidores',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.5,
    ratingCount: 186,
    assets: ['WINFUT'],
    operations: { total: 974, wins: 823, losses: 151 },
    resultPoints: 32.60,
    price: 'R$ 272,99',
  },
  {
    thumbnail: imgGetProfit,
    name: 'Get Profit One',
    planName: 'Copy Invest | Get Profit One',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.0,
    ratingCount: 54,
    assets: ['WINFUT'],
    operations: { total: 421, wins: 260, losses: 161 },
    strategiesCount: 1,
    operatingSince: 'set/2024',
    resultPoints: -45.90,
    price: 'R$ 189,90',
  },
  {
    thumbnail: imgConnectGainDiscount,
    name: 'ConnectGain Master Pass',
    planName: 'Copy Invest | ConnectGain Pass',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    assets: ['WDOFUT', 'WINFUT'],
    operations: { total: 475, wins: 323, losses: 152 },
    strategiesCount: 2,
    operatingSince: 'mar/2025',
    resultPoints: 99.20,
    price: 'R$ 2.150,00',
    discountLabel: '-30%',
  },
  {
    thumbnail: imgMalka,
    name: 'MK Moderada',
    planName: 'Copy Invest | Malka Investimentos Principal',
    description: 'Foco em tendências com gestão ativa de risco.',
    rating: 4.7,
    ratingCount: 121,
    assets: ['WINQ25', 'WINFUT'],
    operations: { total: 502, wins: 340, losses: 162 },
    strategiesCount: 3,
    operatingSince: 'abr/2023',
    resultPoints: 61.05,
    price: 'R$ 155,10',
  },
  {
    thumbnail: imgBitRobos,
    name: 'BIT - Robôs Investidores',
    planName: 'Copy Invest | Robôs Investidores',
    description: 'Carteira diversificada con estratégias para diferentes cenários de mercado.',
    rating: 4.6,
    ratingCount: 210,
    assets: ['WINFUT'],
    operations: { total: 830, wins: 640, losses: 190 },
    strategiesCount: 2,
    operatingSince: 'fev/2024',
    resultPoints: 145.75,
    price: 'R$ 272,99',
  },
];

export const TOTAL_STRATEGIES_COUNT = 48;
export const STRATEGIES_PER_PAGE = 9;

// There are only STRATEGIES.length real mock cards, so other pages reuse them in a
// rotated order (shifted by a step coprime with the list length) to look distinct.
const ROTATION_STEP = 7;

export function getStrategiesForPage(page: number): StrategyCardProps[] {
  const start = (page - 1) * STRATEGIES_PER_PAGE;
  const end = Math.min(start + STRATEGIES_PER_PAGE, TOTAL_STRATEGIES_COUNT);
  const count = Math.max(0, end - start);
  const pageOffset = (page - 1) * ROTATION_STEP;

  return Array.from({ length: count }, (_, i) => {
    const sourceIndex = (start + i + pageOffset) % STRATEGIES.length;
    return STRATEGIES[sourceIndex];
  });
}
